FROM node:22.12.0 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli@20.3.12
RUN npm ci
COPY . .
RUN ng build --configuration production

FROM nginx:alpine

COPY --from=builder /app/dist/crypto-platform/browser /usr/share/nginx/html
RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
