export const WALLET_LABELS = {
    portfolioValue: 'Стоимость портфеля',
    freeAmount: 'Свободные средства',
    assets: 'Активы',
    favourites: 'Избранное',
    emptyList: 'Список пуст',
    deal: 'Сделки с',
    available: 'В наличии',
    purchase: 'Покупка',
    purchaseConfirm: 'Хотите совершить покупку?',
    buy: 'Купить',
    sale: 'Продажа',
    saleConfirm: 'Хотите совершить продажу?',
    sell: 'Продать',
};
